### ISSUE TITLE
The buttons for changing the image position are not working

### ISSUE THREAD

**Issue by AZCodingAccount** [enzedonline/quill-blot-formatter2#12]
hello,The buttons for changing the image position are not working. What could be the reason for this?
<img width="848"  alt="image" src="https://github.com/user-attachments/assets/6ef9e7c5-1a18-4d84-ae5a-798eaf055e6d">

version:
1. `quill:2.0.2`
2. ` "@enzedonline/quill-blot-formatter2": "~2.2.2",`

my code
```javascript
import BlotFormatter2 from '@enzedonline/quill-blot-formatter2'

Quill.register('modules/blotFormatter2', BlotFormatter2)

const options = {
  theme: 'snow',
  modules: {
    toolbar: !props.hideTopBar
      ? {
          container: [
            ['emphasize-button'], // 自定义工具栏
            ['bold', 'italic', 'underline', 'strike'],
            ['link', 'image'],
            [{ color: [] }, { background: [] }],
            [{ header: 1 }, { header: 2 }, { header: 3 }],
            [{ list: 'ordered' }, { list: 'bullet' }, { list: 'check' }],
            ['blockquote', 'code-block'],
            [{ size: ['small', false, 'large', 'huge'] }]
          ],
          handlers: {
            'emphasize-button': emphasizeButtonHandler
          }
        }
      : false,
    keyboard: {
      bindings: {
        emphasize: {
          key: '8',
          shortKey: true, // 这会使用 Ctrl 在 Windows/Linux 上，使用 Cmd 在 Mac 上
          handler: emphasizeButtonHandler
        }
      }
    },
    blotFormatter2: {}
  }
}
```
css:
```css
.ql-toolbar.ql-snow {
  width: 840px;
}

.ql-emphasize-button {
  width: 24px !important;
  height: 24px !important;
  color: red !important; /* 星号的颜色 */
  cursor: pointer !important;
}

.ql-emphasize-button::after {
  font-size: 24px;
  content: '*' !important; /* 使用星号作为内容 */
}

/* 去除文本格式按钮之间的间距 */
.ql-toolbar .ql-formats:has(.ql-emphasize-button) {
  margin-right: 0;
}

/* 自定义hover文字样式 */
[data-title] {
  position: relative;
}

[data-title]:hover::before {
  content: attr(data-title);
  position: absolute;
  bottom: 100%;
  left: 100%;
  transform: translateX(-30px);
  background: black;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  white-space: nowrap;
  font-size: 12px;
  pointer-events: none;
  opacity: 1;
  transition: opacity 0.3s;
}

/* 图片样式 */

.ql-editor {
  overflow-y: auto;
}

.ql-container {
  overflow: hidden;
}
```
